Спринт 15. Домашнее задание. Разнесён код по пакетам presentation, data
TanyaRul/PlaylistMaker pull request #8
Opened 2023-06-14 13:50 UTC by TanyaRul

2023-06-14 15:17 UTC, NoDopezzz requested changes

2023-06-14 15:17 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/search/SearchActivity.kt
> +import com.example.playlistmaker.data.network.ItunesApi
⚠️ Чтобы проверить себя в выполнении правил зависимостей - достаточно обратить внимание на импорты. В слое `presentation` у нас не могут быть никаких  импортов со слоя `data`. К классам `SearchHistory`, `TracksSearchResponse` и `ItunesApi` мы должны обращаться сторого через `domain` модуль.

2023-06-14 15:17 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/search/SearchActivity.kt
> +                .enqueue(object : Callback<TracksSearchResponse> {
⚠️ Логика запросов в сеть должна происходить на уровне `data` внутри специально созданного класса `Repository`. Обрати внимание на практические примеры в материалах 15 спринта

2023-06-14 15:17 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/data/SearchHistory.kt
> +            App.sharedPrefs
⚠️ Не очень хорошо обращаться к `App` классу напрямую из `data` слоя. Чтобы этого избежать, само создание `SharedPreference` мы можем перенести в `SearchHistory`. А `SearchHistory` передавать лишь `applicationContext`.

⏫ Также мы можем переименовать `SearchHistory` на `SearchRepository`.

2023-06-15 14:31 UTC, TanyaRul commented
Вроде бы задача по экрану "Поиск" описывалась как бонусная, т.е. необязательная для этого этапа? Или я неправильно поняла? И по теории работа по этому экрану будет в будущих спринтах: "Теперь осталось освободить MoviesActivity от лишней логики и определить, кто будет использовать интерактор и как полученные данные попадут на экран. Но это задание уже на будущие спринты." Интерфейсы для связи слоёв добавила, но как разобрать код из класса [SearchActivity]  пока что не представляю. У других студентов из моей когорты задание приняли без этой задачи.

2023-07-09 14:39 UTC, merged